workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Gerar plataforma Android
        script: flutter create --platforms=android .
      - name: Atualizar pacotes
        script: |
          flutter pub get
          flutter pub upgrade
      - name: Gerar icone do app
        script: dart run flutter_launcher_icons
      - name: Build APK
        script: flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
