name: app_colorir
description: App de desenhos para imprimir e colorir, com impressão direta via Bluetooth/Wi-Fi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.13.0
  pdf: ^3.11.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/categorias/animais/
    - assets/categorias/dinossauros/
    - assets/categorias/veiculos/
    - assets/categorias/datas_comemorativas/
    - assets/categorias/princesas/
    - assets/categorias/unicornio/
    - assets/categorias/gatinhos/
    - assets/categorias/pandinhas/
    - assets/categorias/cristao/
    - assets/categorias/animais_bosque/
    - assets/categorias/doces_fofos/
    - assets/categorias/cactus/
    - assets/categorias/raposinha/
    - assets/categorias/monstros_fofos/
    - assets/categorias/jardim/
    - assets/categorias/dragao/
    - assets/categorias/monster_truck/
    - assets/categorias/outros/
