name: app_colorir
description: App Flutter (Android) de desenhos para imprimir e colorir.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Versoes cravadas: seguras, testadas e compativeis com Android novo (sem quebrar o Kotlin)
  printing: ^5.11.1
  pdf: ^3.10.8
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  image: ^4.1.7
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icone_app_colorir.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/categorias/animais/
    - assets/categorias/dinossauros/
    - assets/categorias/veiculos/
    - assets/categorias/datas_comemorativas/
    - assets/categorias/princesas/
    - assets/categorias/unicornio/
    - assets/categorias/gatinhos/
    - assets/categorias/pandinhas/
    - assets/categorias/cristao/
    - assets/categorias/animais_bosque/
    - assets/categorias/doces_fofos/
    - assets/categorias/cactus/
    - assets/categorias/raposinha/
    - assets/categorias/monstros_fofos/
    - assets/categorias/jardim/
    - assets/categorias/dragao/
    - assets/categorias/monster_truck/
    - assets/categorias/outros/
